AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app

    Sample SAM Template for sam-app
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3


Resources:

    JwtValidatorFunc:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: validate-jwt/
            Handler: validate-jwt.handler
            Runtime: nodejs8.10
            Events:
                JwtValidatorApi:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /api/jwt-validation
                        Method: post

    CorsPreflightFunc:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: cors-preflight/
            Handler: cors-preflight.handler
            Runtime: nodejs8.10
            Events:
                JwtValidatorApi:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /api/jwt-validation
                        Method: options

Outputs:

    JwtValidatorApi:
      Description: "API Gateway endpoint base"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com"

    JwtValidatorFunc:
      Description: "Lambda Function ARN"
      Value: !GetAtt JwtValidatorFunc.Arn

    JwtValidatorFuncIamRole:
      Description: "Implicit IAM Role"
      Value: !GetAtt JwtValidatorFuncRole.Arn
